SELECT $P{date1} as dt1, $P{date2} as dt2, V.KD_PUSKESMAS, V.NAMA_PUSKESMAS, V.UNIT,  
SUM(IF(UCASE(V.JENIS_KELAMIN) = 'L', 1,0)) AS `L`, 
SUM(IF(UCASE(V.JENIS_KELAMIN) = 'P', 1,0)) AS `P`,
COUNT(V.KD_KUNJUNGAN) AS TOTAL 
FROM vw_rpt_kunjungan AS V WHERE UCASE(V.KD_UNIT_LAYANAN)='PUSKESMAS' AND KD_PUSKESMAS = $P{parameter1} AND V.TGL_MASUK 
BETWEEN $P{date1} AND $P{date2}
GROUP BY V.KD_UNIT_LAYANAN, V.UNIT;