SELECT P.KD_PUSKESMAS, P.TGL_PELAYANAN, D.KD_PENYAKIT, COUNT(D.KD_PELAYANAN) AS TOTAL FROM  pel_diagnosa D INNER JOIN pelayanan P
ON D.KD_PELAYANAN=P.KD_PELAYANAN
GROUP BY P.KD_PUSKESMAS, P.TGL_PELAYANAN, D.KD_PENYAKIT;
